-- Tabela para armazenar informações pessoais e links
create table profile (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  bio text,
  avatar_url text,
  github_link text,
  linkedin_link text,
  resume_link text
);

-- Tabela para armazenar os projetos
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  github_link text,
  project_link text,
  doc_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inserir dados iniciais (Exemplo baseado no seu JSON atual)
-- Você pode rodar isso no SQL Editor do Supabase

-- Dados do Perfil
insert into profile (name, role, bio, avatar_url, github_link, linkedin_link, resume_link)
values (
  'Alvaro Pereira',
  'Desenvolvedor de Softwares',
  'Desenvolvedor Python especializado em automação e integração de sistemas, com experiência em processamento e analise de dados. Busco evoluir constantemente e entregar soluções práticas, criativas, eficientes e bem estruturadas.',
  'yo.jpg', -- Você precisará fazer upload da imagem no Storage do Supabase e pegar a URL pública, ou usar o caminho relativo se mantiver local, mas o ideal é Storage.
  'https://github.com/AlvaroPereir4',
  'https://www.linkedin.com/in/alvaro-pereira-b5b2a8227/',
  'https://drive.google.com/file/d/1TKDsOi6X2mU1baOEBZP-WcHKDACbzRKl/view?usp=sharing'
);

-- Habilitar RLS (Row Level Security) é uma boa prática, mas para começar simples:
-- Permitir leitura pública
alter table profile enable row level security;
create policy "Public profiles are viewable by everyone" on profile for select using (true);

alter table projects enable row level security;
create policy "Public projects are viewable by everyone" on projects for select using (true);

-- Para o admin (escrita), você precisará estar logado ou configurar políticas permissivas (cuidado em produção).
-- Exemplo de política permissiva para desenvolvimento local (NÃO RECOMENDADO PARA PRODUÇÃO):
-- create policy "Enable insert for everyone" on projects for insert with check (true);
